### ISSUE TITLE
Roku emulator not found by Sofabaton

### ISSUE THREAD

**Issue by cpolhout** [martonperei/emulated_roku#6]
The emulator is not found by the Sofabaton remote (X1). Maybe also other clients can't find it. This is due to missing headers in the multicast-response. I fixed it in this PR: https://github.com/martonperei/emulated_roku/pull/5

**Comment by popy2k14** [comment]
@cpolhout Tried that fixed version with my SofaBaton X1 and sadly it never get's found.

Is it possible for you to get some wiresharks and test if the current app find's the emulated roku?
If not: Do you have an real roku to get some wiresharks of the actual headers it sends?

thx
